# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'ru'
locale_dirs = ['./locale/']
gettext_compact = False

html_theme_path = ["_theme", "djbook/_theme"]
html_theme = "djbook"
